// Copyright (c) Choreo contributors

// Auto-generated by update_field_dimensions.py
package choreo.util;

public class FieldDimensions {

    public static final double FIELD_LENGTH = 17.548;
    public static final double FIELD_WIDTH = 8.052;
}
